### ISSUE TITLE
v0 TODO's

### ISSUE THREAD

**Issue by iejMac** [iejMac/GPTReview#6]
- [x] Get PR link into review python func
- [x] Get .patch into string in python file
- [x] OpenAI API take input
- [x] figure out good prompt
- [x] output review
- [x] only works if you're collaborator

**Comment by iejMac** [comment]
Me too

**Comment by iejMac** [comment]
try

**Comment by iejMac** [comment]
issue

**Comment by iejMac** [comment]
ok
