### ISSUE TITLE
v1 TODO's

### ISSUE THREAD

**Issue by iejMac** [iejMac/GPTReview#8]
- [x] check if collaborator
- [x] no whitespace
- [x] check if PR issue comment
- [x] make GitHub-actions respond and not me (use GitHub.token)
- [x] stress test (large PR etc.)

**Comment by rom1504** [comment]
make it work easily for any repo

**Comment by iejMac** [comment]
hi there 

  what is 
 up
